run_test: 
	python protonet.py --test --log_dir "/Users/robin.ranabhat/extra/MOOC/CS330_Meta-Learning_RL/2021/CS330-2021-Meta-Learning/hw2/starter/logs/protonet/omniglot.way:5.support:5.query:15.lr:0.001.batch_size:16" --checkpoint_step 1400 --num_support 5  --num_way 5
